### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Dalethium** [m1k3s/reptiles#13]
https://github.com/m1k3s/reptiles/blob/806ca86237a289fe62836701525f11b89ed08200/reptiles/common/Reptiles.java#L118

You kept this in and removed that class, causes this crash

`Caused by: java.lang.ClassNotFoundException: com.reptiles.common.CommonProxyReptiles
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	... 31 more
Caused by: java.lang.NullPointerException`

**Comment by m1k3s** [comment]
Well, that was stupid. I guess I never finished removing CommonProxy code. Thanks. Fixed.
