### ISSUE TITLE
World Gen NullPointer

### ISSUE THREAD

**Issue by Isep321** [m1k3s/reptiles#2]
This error appears during world gen, isn't fatal though. 

```
[20:32:30] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
at net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry.hashCode(SourceFile:40)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)
at net.minecraft.entity.ai.EntityAITasks.func_75776_a(SourceFile:56)
at com.reptiles.common.EntityTurtle.func_184651_r(EntityTurtle.java:70)
at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:104)
at net.minecraft.entity.EntityCreature.<init>(SourceFile:18)
at net.minecraft.entity.EntityAgeable.<init>(EntityAgeable.java:27)
at net.minecraft.entity.passive.EntityAnimal.<init>(SourceFile:28)
at net.minecraft.entity.passive.EntityTameable.<init>(SourceFile:30)
at com.reptiles.common.EntityTurtle.<init>(EntityTurtle.java:53)
at com.reptiles.common.EntityTortoise.<init>(EntityTortoise.java:32)
... 13 more
[20:32:30] [Server thread/INFO] [STDERR]: [net.minecraft.world.WorldEntitySpawner:func_77191_a:269]: java.lang.reflect.InvocationTargetException
at sun.reflect.GeneratedConstructorAccessor45.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:265)
at net.minecraft.world.gen.ChunkProviderOverworld.func_185931_b(ChunkProviderOverworld.java:454)
at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298)
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:268)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
at java.lang.Thread.run(Thread.java:745)
[20:32:30] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
at net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry.hashCode(SourceFile:40)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)
at net.minecraft.entity.ai.EntityAITasks.func_75776_a(SourceFile:56)
at com.reptiles.common.EntityTurtle.func_184651_r(EntityTurtle.java:70)
at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:104)
at net.minecraft.entity.EntityCreature.<init>(SourceFile:18)
at net.minecraft.entity.EntityAgeable.<init>(EntityAgeable.java:27)
at net.minecraft.entity.passive.EntityAnimal.<init>(SourceFile:28)
at net.minecraft.entity.passive.EntityTameable.<init>(SourceFile:30)
at com.reptiles.common.EntityTurtle.<init>(EntityTurtle.java:53)
at com.reptiles.common.EntityTortoise.<init>(EntityTortoise.java:32)
... 13 more
```

**Comment by m1k3s** [comment]
Thanks, I missed that. it is fixed in the latest version. I uploaded to Curse.
